# Generated by Django 2.2.2 on 2019-07-09 04:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)])),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('image', models.ImageField(default='defo', upload_to='pictweet/images/')),
                ('date_time', models.DateTimeField()),
                ('like_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictweet.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictweet.Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='pictweet.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('created_at', models.DateTimeField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictweet.Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictweet.User')),
            ],
        ),
    ]
