# Generated by Django 2.2.3 on 2019-07-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictweetpython2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
